### ISSUE TITLE
Post list fixes

### ISSUE THREAD

**Issue by BackSpace16** [FEIProjectTeam/asos#34]
## TODO
- [x] masonry layout fix
- [x] white background on image bottom corners on title hover
- [x] likes functionality on list page
